In [5]:
import pandas as pd

from sklearn.datasets import load_digits

dig = load_digits()

dir(dig)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [7]:
df = pd.DataFrame(dig.data,columns = dig.feature_names)

In [9]:
df

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_6,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,0.0,0.0,4.0,10.0,13.0,6.0,0.0,0.0,0.0,1.0,...,4.0,0.0,0.0,0.0,2.0,14.0,15.0,9.0,0.0,0.0
1793,0.0,0.0,6.0,16.0,13.0,11.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,6.0,16.0,14.0,6.0,0.0,0.0
1794,0.0,0.0,1.0,11.0,15.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,9.0,13.0,6.0,0.0,0.0
1795,0.0,0.0,2.0,10.0,7.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,5.0,12.0,16.0,12.0,0.0,0.0
1796,0.0,0.0,10.0,14.0,8.0,1.0,0.0,0.0,0.0,2.0,...,8.0,0.0,0.0,1.0,8.0,12.0,14.0,12.0,1.0,0.0

In [11]:
x = df

y = dig.target

In [19]:
from sklearn.preprocessing import StandardScaler

so = StandardScaler()

xsc = so.fit_transform(x)

xsc

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [23]:
from sklearn.model_selection import train_test_split

xo_train, xo_test, yo_train, yo_test = train_test_split(
    xsc, y, test_size=0.2)

In [39]:
from sklearn.linear_model import LogisticRegression

mod = LogisticRegression()

mod.fit(xsc,y)

mod.score(xsc,y)

xsc.shape

(1797, 64)

In [41]:
from sklearn.decomposition import PCA

pop = PCA(0.95)

xsc = pop.fit_transform(xsc)

In [43]:
xsc.shape

(1797, 40)

In [45]:
xpca_train, xpca_test, yo_train, yo_test = train_test_split(
    xsc, y, test_size=0.2)

In [49]:
mod.fit(xpca_train,yo_train)

mod.score(xpca_train,yo_train)

0.9937369519832986

In [91]:
df = pd.read_csv("heart.csv")

In [95]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [97]:
df = df[ df['Cholesterol'] <= (df['Cholesterol'].mean() + 3*df['Cholesterol'].std())]

In [101]:
df = df[ df['Cholesterol'] >= (df['Cholesterol'].mean() - 3*df['Cholesterol'].std())]

In [107]:
df = df[ df['RestingBP'] <= (df['RestingBP'].mean() + 3*df['RestingBP'].std())]
df = df[ df['RestingBP'] >= (df['RestingBP'].mean() - 3*df['RestingBP'].std())]


df = df[ df['FastingBS'] <= (df['FastingBS'].mean() + 3*df['FastingBS'].std())]
df = df[ df['FastingBS'] >= (df['FastingBS'].mean() - 3*df['FastingBS'].std())]



df = df[ df['MaxHR'] <= (df['MaxHR'].mean() + 3*df['MaxHR'].std())]
df = df[ df['MaxHR'] >= (df['MaxHR'].mean() - 3*df['MaxHR'].std())]


df = df[ df['Oldpeak'] <= (df['Oldpeak'].mean() + 3*df['Oldpeak'].std())]
df = df[ df['Oldpeak'] >= (df['Oldpeak'].mean() - 3*df['Oldpeak'].std())]

In [111]:
df.describe()

df.shape

(899, 12)

In [127]:
df

x = df.drop('HeartDisease',axis = 'columns')

x

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up
...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up

In [129]:
x

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up
...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up

In [131]:
from sklearn.preprocessing import StandardScaler

z = StandardScaler()
x = z.fit_transform(x)

ValueError: could not convert string to float: 'M'

In [133]:
y = df.HeartDisease

In [139]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

x[['ExerciseAngina','Sex','ChestPainType',"RestingECG","ST_Slope"]] = x[['ExerciseAngina','Sex','ChestPainType',"RestingECG","ST_Slope"]].apply(le.fit_transform)

x

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,1,1,140,289,0,1,172,0,0.0,2
1,49,0,2,160,180,0,1,156,0,1.0,1
2,37,1,1,130,283,0,2,98,0,0.0,2
3,48,0,0,138,214,0,1,108,1,1.5,1
4,54,1,2,150,195,0,1,122,0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1
914,68,1,0,144,193,1,1,141,0,3.4,1
915,57,1,0,130,131,0,1,115,1,1.2,1
916,57,0,1,130,236,0,0,174,0,0.0,1
917,38,1,2,138,175,0,1,173,0,0.0,2

In [141]:
from sklearn.preprocessing import StandardScaler

z = StandardScaler()
x = z.fit_transform(x)

In [143]:
x

array([[-1.42815446,  0.515943  ,  0.2245723 , ..., -0.8229452 ,
        -0.85546862,  1.04249607],
       [-0.47585532, -1.93819859,  1.27063705, ..., -0.8229452 ,
         0.13751561, -0.62216462],
       [-1.7455875 ,  0.515943  ,  0.2245723 , ..., -0.8229452 ,
        -0.85546862,  1.04249607],
       ...,
       [ 0.3706328 ,  0.515943  , -0.82149245, ...,  1.21514774,
         0.33611246, -0.62216462],
       [ 0.3706328 , -1.93819859,  0.2245723 , ..., -0.8229452 ,
        -0.85546862, -0.62216462],
       [-1.63977649,  0.515943  ,  1.27063705, ..., -0.8229452 ,
        -0.85546862,  1.04249607]])

In [175]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=30)

In [177]:
from sklearn.decomposition import PCA

solo = PCA(0.95)

X_train = solo.fit_transform(X_train)
X_test = solo.fit_transform(X_test)

In [207]:
from sklearn.svm import SVC

from sklearn.ensemble import RandomForestClassifier

from sklearn.linear_model import LogisticRegression

from sklearn.naive_bayes import GaussianNB,MultinomialNB

from sklearn.tree import DecisionTreeClassifier


sop = RandomForestClassifier()

sop.fit(X_train,y_train)


sop.score(X_train,y_train)

1.0

In [197]:
model_parms = {
    'svm': {
        'model':SVC(gamma='auto'),
        'params':{
            'C':[1,10,20],
            'kernel':['rbf','linear']
        }
    },
    'random_forest': {
        'model':RandomForestClassifier(),
        'params':{
            
            'n_estimators':[1,5,10]
        }
    },
    'logistic_regression': {
        'model':LogisticRegression(solver = 'liblinear',multi_class = 'auto'),
        'params':{
            'C':[1,5,10]
        }
    },
    
    'decision_tree': {
        'model':DecisionTreeClassifier(),
        'params':{
            'criterion': ['gini','entropy'],
        }
    }
}

In [201]:
from sklearn.model_selection import GridSearchCV

scores = []

for m,k in model_parms.items():
   

    clf = GridSearchCV(k['model'],k['params'],cv=5,return_train_score = False)
    clf.fit(x,y)
    scores.append({'model':m,'best_scores':clf.best_score_,'best_params':clf.best_params_})

In [203]:
scores

[{'model': 'svm',
  'best_scores': 0.8263997517070143,
  'best_params': {'C': 1, 'kernel': 'rbf'}},
 {'model': 'random_forest',
  'best_scores': 0.8008255741775295,
  'best_params': {'n_estimators': 10}},
 {'model': 'logistic_regression',
  'best_scores': 0.8019242706393545,
  'best_params': {'C': 1}},
 {'model': 'decision_tree',
  'best_scores': 0.7552017380509001,
  'best_params': {'criterion': 'entropy'}}]